export const leagueLogos: Record<string, string> = {
  "AFL Vic Metro U15 Boys Div 2 2026": "/leagues/aflvicmetro.png",
  "AFL Vic Metro U14 Boys Div 1 2026": "/leagues/aflvicmetro.png",
  "AFL Vic Metro U14 Girls Div 1 2026": "/leagues/aflvicmetro.png",
  "AFL Vic Metro U15 Girls Div 1 2026": "/leagues/aflvicmetro.png",
  "AFL Vic Metro U14 Boys Div 2 2026": "/leagues/aflvicmetro.png",
  "AFL Vic Metro U15 Boys Div 1 2026": "/leagues/aflvicmetro.png",
  "AGSV 2026": "/leagues/agsv.png",
  "AGSV Girls 2026": "/leagues/agsv.png",
  "APS 2026": "/leagues/aps.png",
  "Goulburn Valley League 2026": "/leagues/gvl.png",
  "Goulburn Valley League U18s 2026": "/leagues/gvl.png",
  "Tallangatta and District FL 2026": "/leagues/tallangatta.png",
  "EFNL Division 4 2026": "/leagues/efnl.png",
  "ACC Division 1 2026": "/leagues/acc.png",
  "Ballarat FNL 2026": "/leagues/ballarat.png",
  "Bellarine FL 2026": "/leagues/bellarine.png",
  "Bendigo FNL 2026": "/leagues/bendigo.png",
  "Central Rivers FNL 2026": "/leagues/central-rivers.png",
  "EDFL Division 1 2026": "/leagues/edfl.png",
  "EDFL Division 2 2026": "/leagues/edfl.png",
  "EDFL Division 2 U18.5 2026": "/leagues/edfl.png",
  "EDFL Premier Division 2026": "/leagues/edfl.png",
  "EDFL Premier Division Reserves 2026": "/leagues/edfl.png",
  "EDFL Premier Division U18.5 2026": "/leagues/edfl.png",
  "EDFL Thirds North Division 2026": "/leagues/edfl.png",
  "EFNL Division 1 2026": "/leagues/efnl.png",
  "EFNL Division 2 2026": "/leagues/efnl.png",
  "EFNL Division 3 2026": "/leagues/efnl.png",
  "EFNL Premier Division 2026": "/leagues/efnl.png",
  "Ellinbank District Football League 2025": "/leagues/ellinbank.png",
  "Farrer FL 2026": "/leagues/farrer.png",
  "Geelong and District Football 2026": "/leagues/gdfnl.png",
  "Geelong FNL 2026": "/leagues/geelong.png",
  "Heathcote District FNL 2026": "/leagues/heathcote.png",
  "Interleague 2026": "/leagues/pd.png",
  "Sandringham Dragons 2026": "/leagues/sandringham.png",
  "Hume FNL 2026": "/leagues/hume.png",
  "MPFNL Division 1 2026": "/leagues/mpfnl.png",
  "MPFNL Division 2 2026": "/leagues/mpfnl.png",
  "MPFNL Division 1 Womens 2026": "/leagues/mpfnl.png",
  "Murray FL 2026": "/leagues/murray.png",
  "NFNL Division 1 2026": "/leagues/nfnl.png",
  "NFNL Division 2 2026": "/leagues/nfnl.png",
  "NFNL Division 3 2026": "/leagues/nfnl.png",
  "North Central FL 2026": "/leagues/north-central.png",
  "North West FL 2026": "/leagues/north-west.png",
  "North West FL Womens 2026": "/leagues/north-west.png",
  "NTFA Premier Division 2026": "/leagues/ntfa.png",
  "NTFA Premier Division Womens 2026": "/leagues/ntfa.png",
  "NTFA Division 1 Womens": "/leagues/ntfa.png",
  "Outer East Division 1 2026": "/leagues/outer-east.png",
  "Outer East Premier Division 2026": "/leagues/outer-east.png",
  "Ovens and Murray 2026": "/leagues/ovens-and-murray.png",
  "Perth FL A Grade Mens 2026": "/leagues/perth.png",
  "Perth FL A Grade Women 2026": "/leagues/perth.png",
  "Practice Kilsyth 2026": "/leagues/pd.png",
  "Bachar Houli Academy 2026": "/leagues/pd.png",
  "Practice South Belgrave 2026": "/leagues/pd.png",
  "PSA 2026": "/leagues/psa.png",
  "Riddell District FNL 2026": "/leagues/riddell.png",
  "Riddell District FNL Womens 2026": "/leagues/riddell.png",
  "Riverina FL 2026": "/leagues/riverina.png",
  "Riverina FNL U18s": "/leagues/riverina.png",
  "SFL (TAS) Premier League 2026": "/leagues/sfl.png",
  "SFL (TAS) Premier League Womens 2026": "/leagues/sfl.png",
  "SFNL Division 1 2026": "/leagues/sfnl.png",
  "SFNL Division 2 2026": "/leagues/sfnl.png",
  "SFNL Division 3 2026": "/leagues/sfnl.png",
  "SFNL Division 4 2026": "/leagues/sfnl.png",
  "Sunraysia FNL 2026": "/leagues/sunraysia.png",
  "VAFA Premier A 2026": "/leagues/vafa.png",
  "VAFA Premier B 2026": "/leagues/vafa.png",
  "VAFA Premier C 2026": "/leagues/vafa.png",
  "VAFA Division 1 2026": "/leagues/vafa.png", 
  "VAFA Division 2 2026": "/leagues/vafa.png",
  "West Gippsland FL 2026": "/leagues/west-gippsland.png",
  "WFNL Division 1 2026": "/leagues/wfnl.png",
  "WFNL Division 2 2026": "/leagues/wfnl.png",
  "Wimmera FNL 2026": "/leagues/wimmera.png",
  "Central Highlands FL 2026": "/leagues/chfl.png",
  "Colac and District FNL 2026": "/leagues/colac.png",
  "Country Football WA 2026": "/leagues/country-football.png",
  "EDFL Womens Premier Division 2026": "/leagues/edfl.png",
  "EFNL Division 2 Reserves 2026": "/leagues/efnl.png",
  "EFNL Division 2 U19s 2026": "/leagues/efnl.png",
  "EFNL Division 4 Reserves 2026": "/leagues/efnl.png",
  "EFNL Premier Division Women 2026": "/leagues/efnl.png",
  "Horsham District FNL 2026": "/leagues/horsham.png",
  "Influencer Games 2026": "/leagues/pd.png",
  "KDFNL 2026": "/leagues/kdfnl.png",
  "Loddon Valley FNL 2026": "/leagues/loddon-valley.png",
  "MCDFNL 2026": "/leagues/mcdfnl.png",
  "Mid Gippsland FNL 2026": "/leagues/mid-gippsland.png",
  "NFNL Division 2 Womens 2026": "/leagues/nfnl.png",
  "North Gippsland FNL 2026": "/leagues/north-gippsland.png",
  "NTFA Division 1 2026": "/leagues/ntfa.png",
  "NTFA Division 1 Womens 2026": "/leagues/ntfa.png",
  "Outer East Division 1 Womens 2026": "/leagues/outer-east.png",
  "Ovens and King FL 2026": "/leagues/ovens-and-king.png",
  "Ovens and Murray U18s 2026": "/leagues/ovens-and-murray.png",
  "Perth FL C1 Men 2026": "/leagues/perth.png",
  "Picola and District 2026": "/leagues/picola-and-district.png",
  "Practice APS 2026": "/leagues/practice-aps.png",
  "River Murray FL 2026": "/leagues/river-murray.png",
  "Riverland Football League 2026": "/leagues/riverland.png",
  "Rivery Murray FL 2026": "/leagues/river-murray.png",
  "SFL (SA) A Grade 2026": "/leagues/sflsa.png",
  "SFL (TAS) Community League 2026": "/leagues/sfl.png",
  "SMJFL U16 Girls Division 1 2026": "/leagues/smjfl.png",
  "SMJFL U18 Girls Division 1 2026": "/leagues/smjfl.png",
  "South West FL 2026": "/leagues/south-west.png",
  "State Rep U16 2026": "/leagues/state-rep.png",
  "State Representative 2026": "/leagues/pd.png",
  "Tas Devils Academy 2026": "/leagues/tas-rep.png",
  "TAS Representative Series Men 2026": "/leagues/tas-rep.png",
  "TAS Representative Series Women 2026": "/leagues/tas-rep.png",
  "VAFA Division 2 Womens 2026": "/leagues/vafa.png",
  "VAFA Premier A Womens 2026": "/leagues/vafa.png",
  "VAFA U19 Division 2 2026": "/leagues/vafa.png",
  "VAFA U19 Premier Division 2026": "/leagues/vafa.png",
  "West Gippsland FL Reserves 2026": "/leagues/west-gippsland.png",
  "YJFL U12 Division 3 2026": "/leagues/yjfl.png",
  "YJFL U15 Division 1 2026": "/leagues/yjfl.png"
};
